### ISSUE TITLE
Bug: reply::json error: key must be a string

### ISSUE THREAD

**Issue by 0xMimir** [openmina/openmina#125]
After running:
```sh
cargo run --bin openmina -- node
```
or 
```sh
cargo build -r
./target/release/openmina node
```

And then trying to fetch `/state`, I get 200 OK for response status but empty body for response and in node shows
```sh
2023-11-03T17:34:23.070216Z ERROR warp::reply: reply::json error: key must be a string
```

Calling `/state` route works for first 10-20 seconds, then it stops working, and after 4-5 minutes, it starts working again, this issue appears on both [main](https://github.com/openmina/openmina/tree/main) and on [develop](https://github.com/openmina/openmina/tree/develop) branch

**Comment by akoptelov** [comment]
The error is fixed. Also JsonPath support is implemented for filtering, see #283
