### ISSUE TITLE
As a developer, I need to make genesis ledger configurable

### ISSUE THREAD

**Issue by binier** [openmina/openmina#285]

**Comment by tizoc** [comment]
Regarding this, I would skip that intermediary tool and just load the JSON directly.

**Comment by binier** [comment]
@tizoc yeah I want that too, but I'm not sure how to correctly represent types possible in daemon.json

From what I've seen, there are many ways to represent things, e.g. just account pub key and balance, the rest default I guess. Or you could encode more parts of the account.

I'd rather do what I need for testing, leave the hardcoded berkeley ledger there for now, but I'll make config type extensible, so that we can later extend it for daemon.json support.

It's just that if we go with daemon.json approach, along with supporting that encoding, I'd need to take care of a lot of other things, like updating readme, extending cli, including daemon.json in testing setups, etc..

**Comment by binier** [comment]
Support for daemon.json based configuration tracked in #299
