### ISSUE TITLE
Refactor enums to address `large_enum_variant` warnings

### ISSUE THREAD

**Issue by tizoc** [openmina/openmina#360]
The codebase contains a bunch of enums that trigger `large_enum_variant` Clippy warnings.

### Task
- Run `cargo clippy -- -A clippy::all -W clippy::large_enum_variant` to identify such enums.
- Use `Box` to minimize variant sizes where applicable.

**Comment by tizoc** [comment]
This may be covered already by #302

**Comment by 0xMimir** [comment]
Fixed in #494 and #498
