### ISSUE TITLE
Issue connecting to node running on localhost

### ISSUE THREAD

**Issue by 0xMimir** [openmina/openmina#361]
When running 2 nodes on same computer, they don't connect one to another. First node has remote peers, while second has only first node as peer.

When following query is ran on graphql interface:
```graphql
query MyQuery {
  syncStatus
}
```

First node gets to `BOOTSTRAP` and later to `SYNCED`, while second node is stuck at `LISTENING`

Steps to reproduce:

In one terminal run:
```sh
export OPENMINA_DISCOVERY_FILTER_ADDR=false
cargo run --bin openmina -- node -s 5KgwoC4tGKNE4G3XP6JDYXKPSMyzjyEfKxdACsnqwTXBaSD75y4
```

In second terminal run:
```sh
export OPENMINA_DISCOVERY_FILTER_ADDR=false
cargo run --bin openmina -- node -P /ip4/127.0.0.1/tcp/8302/p2p/12D3KooWJDihKQfdBUgbRQpMUyUj7avdaJUqin1hJGGQKE8oGF72 --libp2p-port 4001 -p 4903
```

This same issue also happens when node is ran on another computer on local network.

**Comment by binier** [comment]
@akoptelov @vlad9486 Could you take a look?

**Comment by akoptelov** [comment]
@0xMimir thanks for posting this issue.

I can see following problems:
- Connection to the Rust node. The second node constantly disconnects from the first one with the reason `transition frontier RPC timeout`. Looks like we don't handle that properly.
- Peers disovery. With the current implementation, a peer can have only one IP address, while Kademlia provides multiple addresses. The `OPENMINA_DISCOVERY_FILTER_ADDR` is rather a workaround for this issue, as when connecting to a public network we want to filter out local addresses, while in testing we should use localhost ones. In other words, with that variable set to `true` the node will inaccessible addresses for peers outside of the local network. Also I can see some errors regarding Kademlia in the log. The test suite for Kademlia currently is under construction.

@binier FYI
