### ISSUE TITLE
As a developer, I want to make sure that the node is compatible with devnet, so that I can connect to it

### ISSUE THREAD

**Issue by tizoc** [openmina/openmina#385]
Right now the node is compatible with the current berkeley testnet (tag `2.0.0berkeley_rc1`), but there are some incompatible changes that have been introduced [between that release and devnet](https://github.com/MinaProtocol/mina/compare/2.0.0berkeley_rc1...3.0.0devnet).

Relevant PRs/changes:
- [x] https://github.com/MinaProtocol/mina/pull/15298 (not needed, this code is in snarky-rs which we are not using)
- [x] https://github.com/MinaProtocol/mina/pull/15079
  - [x] Revise (we have constants but not config)
- [x] https://github.com/MinaProtocol/mina/pull/15267
- [x] https://github.com/MinaProtocol/mina/pull/15255
- [x] https://github.com/MinaProtocol/mina/commit/6fb600894e7364b9e32be7282ff9838aa8f90749#diff-cf018237f78477ee79b400396de05b8a2555a294cee1416ecafd5df2add83afa
  - we do not generate circuits yet, so this doesn't affect our code
- [ ] https://github.com/MinaProtocol/mina/commit/88391e57e9ab2cb9986586cccad9d86ba78ddaa6#diff-03530b50346aa5f8c96ed606fa4dea83160764d4b4e58579616f0a09af2e9b48
- [x] https://github.com/MinaProtocol/mina/pull/15092
- [x] https://github.com/MinaProtocol/mina/pull/15363
- [x] https://github.com/MinaProtocol/mina/pull/15091
- [ ] https://github.com/MinaProtocol/mina/pull/15221 (maybe?)
- [ ] soft zkapp txn limit (partially implemented in the transaction pool already, check block production too)
- [x] https://github.com/MinaProtocol/mina/blob/9f38ff1bbeac34cd2e3d3cf516efb2ab30b5163f/src/lib/hash_prefixes/hash_prefixes.ml#L38-L40 zkapp body value is different when on mainnet vs testnet
- [x] Dump and update gates data (see: https://github.com/openmina/circuit-blobs/pull/2)
- [x] Produce a genesis ledger json file that we can load
- [x] Update genesis protocol state production so that it can handle the fork

**Comment by tizoc** [comment]
Update: All required code updates should be ready (but this will be confirmed with testing) along with updated circuits data.

Pending:
- [ ] Produce a genesis ledger openmina can load
- [ ] Connect to devnet using this genesis ledger, making sure we can bootstrap, verify snarks and blocks, etc
- [ ] Update proof tests and ensure they work
- [ ] Update CI tests that currently depend on berkeley testnet so that they use devnet instead (for example, the bootstrap test)

**Comment by tizoc** [comment]
Update: All required code updates should be ready (but this will be confirmed with testing) along with updated circuits data.

Pending:
- [x] Produce a genesis ledger openmina can load
  - [ ] Update ledger parsing which is not correctly handling some accounts
- [ ] Connect to devnet using this genesis ledger, making sure we can bootstrap, verify snarks and blocks, etc
- [ ] Update proof tests and ensure they work
   - [x] Non-block proof tests passing
   - [ ] block proof test passing
   - [ ] hashes and checksum values checked against OCaml 
- [ ] Update CI tests that currently depend on berkeley testnet so that they use devnet instead (for example, the bootstrap test) (**partially done**)

**Comment by tizoc** [comment]
Update: more fixes (config and hashes parsing), but computed ChainID is still off.

**Comment by tizoc** [comment]
Update: made some fixes required for mainnet, changed genesis ledger loader so that invalid public keys are also accepted (required because there are two accounts on the mainnet genesis with invalid public keys). Now back to fixing the genesis protocol state reconstruction for devnet. Once it is all working, regenerating the circuit blob data for mainnet should be enough to also have post-hf mainnet support.

**Comment by sebastiencs** [comment]
Fixing block proof generation for `devnet`

**Comment by tizoc** [comment]
Update: genesis protocol state is mostly right, except that either the `last_vrf_output` + `next_epoch.seed` values or `next_epoch.lock_checpoint` are incorrect (fixing the former breaks the later). Trying to figure out how to fix that issue, then the genesis protocol state will match the one produced by the OCaml node.

incorrect vrf output and seed: https://gist.github.com/tizoc/7d26fe1c8bd58ea1a60ba28e5972f1a8/90d79a1bcf3a7d86641b9139d3af8ddc59c9c596

vs

incorrect lock checkpoint: https://gist.github.com/tizoc/7d26fe1c8bd58ea1a60ba28e5972f1a8/344924229d9caf16f74c5c6089d8f2cb0e75ead0

**Comment by sebastiencs** [comment]
Block proof generation has been fixed in https://github.com/openmina/openmina/pull/412/commits/828e11cffe215d812cbde5ed74e805babdb434f8
