### ISSUE TITLE
Replace `structopt` with `clap`

### ISSUE THREAD

**Issue by akoptelov** [openmina/openmina#50]
As it is stated in https://crates.io/crates/structopt,

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.

This is a call for using `clap` instead.

@binier any objections?

**Comment by binier** [comment]
No. Sounds good.

**Comment by akoptelov** [comment]
Fixed as a part of #44
