### ISSUE TITLE
As a developer, I want to store incoming p2p connections information in the state, so that such information is not lost

### ISSUE THREAD

**Issue by tizoc** [openmina/openmina#844]
Currently we keep such information for outgoing connections, but not for incoming ones:

https://github.com/openmina/openmina/blob/b2a21077e716435dc4ab92b62fb7dae6b1c07257/p2p/src/p2p_state.rs#L360

This means that for incoming connections such information is lost and cannot be queried later.

**Comment by tizoc** [comment]
https://github.com/openmina/openmina/pull/846

**Comment by vlad9486** [comment]
- Added `--libp2p-external-addr` option to configure IP address that user wants to declare.
- Fixed incoming connection handling to store `dial_opts` for incoming peer.
- Use configured IP instead of observed address in case where observed IP is local.

TODO: more testing.
