### ISSUE TITLE
As a developer, I need to implement logic for maintaining root snarked ledger, so that rust nodes can bootstrap other nodes

### ISSUE THREAD

**Issue by binier** [openmina/openmina#91]
We synchronize root snarked ledger initially during bootstrap,
but as root block moves, once snarked ledger changes, we need to update our snarked ledger mask.

Once we are bootstrapped, we need to always have snarked ledger mask stored here:
https://github.com/openmina/openmina/blob/ef53e52c4da959d9830d3aa55d96e14ced719d25/node/src/ledger/ledger_service.rs#L70

We need to add logic [here](https://github.com/openmina/openmina/blob/ef53e52c4da959d9830d3aa55d96e14ced719d25/node/src/transition_frontier/transition_frontier_effects.rs#L150) so that when catchup is finished, we update our root snarked ledger if we have to.
There we should compare old chain (`state.transition_frontier.chain`) with new chain (`state.transition_frontier.sync.chain`) and if root snarked ledger is different, we need to update the mask in the service.

No need for garbage collection as it's already done here: https://github.com/openmina/openmina/blob/ef53e52c4da959d9830d3aa55d96e14ced719d25/node/src/ledger/ledger_service.rs#L335

**Comment by tizoc** [comment]
Update: spent some time getting familiarized with the code and implementing the logic, but when testing I found out I went down the wrong path. Unlike in the OCaml node, our staged ledger is not built on top of the snarked ledger, but on top of a copy of it, so by committing the staged ledger the snarked ledger is not being updated. I have to make sure I update the snarked ledger itself now, then make sure that the on-disk files are being properly GCed too.

**Comment by tizoc** [comment]
Update: this is already implemented, but there is still one corner case that needs to be handled (there seems to be some race condition if the best tip changes in between the initial catchup and the first block being applied which causes a required snarked ledger to be missing). A full integration test that ensures other nodes can fully bootstrap from a Rust node is also missing but will be done as part of #103 (which is also required for bootstrapping)

**Comment by tizoc** [comment]
Closing because  #133 got merged already.
