### ISSUE TITLE
Test bootstrap from Berkeley testnet

### ISSUE THREAD

**Issue by akoptelov** [openmina/openmina#97]
The goal is to start an Openmina node and make sure it can connect to the berkeleynet testnet.

Also we need to make sure that Openmina can run without restarts and be in sync with the network.

Checks that need to be performed after starting:
- [x] Node is in sync state
- [x] Node's best tip is the one that of berkeleynet

Checks that need to be performed before restarting:
- [x] Node is in sync state
- [x] Node's best tip is the one that of berkeleynet
- [x] There were no restarts for openmina container

**Comment by akoptelov** [comment]
Currently the test is failing because of #98

**Comment by akoptelov** [comment]
Here are some issues:
- Currently the node cannot discover new peers, and configured peers soon enough disconnect and eventually blacklist it
- Now it is not exactly clear if there are peers connected or not. It seems that a peer might be considered active but be in disconnected state.
- /state RPC is broken, so can't get the whole state to debug p2p issues

**Comment by vlad9486** [comment]
@akoptelov Please, try the newest openmina node from `develop` branch (revision `d0ccf1c`) where peer discovery is merged and the newest debugger `openmina/mina-network-debugger:cb447418`.
